package org.example.ArraysAndHashing;

public class FindTheDifferenceEasy {

    //You are given two strings s and t.
    //
    //String t is generated by random shuffling string s and then add one more letter at a random position.
    //
    //Return the letter that was added to t.

    //Example 1:
    //
    //Input: s = "abcd", t = "abcde"
    //Output: "e"
    //Explanation: 'e' is the letter that was added.
    public static void main(String[] args) {

    }
    public char findTheDifference(String s, String t) {
        return s.charAt(0);
    }
}
