package org.example.ArraysAndHashing;

public class FindTheDifferenceEasy {

    //You are given two strings s and t.
    //
    //String t is generated by random shuffling string s and then add one more letter at a random position.
    //
    //Return the letter that was added to t.

    //Example 1:
    //
    //Input: s = "abcd", t = "abcde"
    //Output: "e"
    //Explanation: 'e' is the letter that was added.
    public static void main(String[] args) {

        String s = "abcd";
        String t = "abcde";
        findTheDifference(s,t);

    }
    public static char findTheDifference(String s, String t) {

        //t-s = znajdz roznice miedzy tymi dwoma stringami i daj ta literke
        
        return s.charAt(0);
    }
}
